[workspace]
authors = ["baka-gourd <36119339+baka-gourd@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "Herodotus"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://mirrors.ustc.edu.cn/pypi/simple"]

[tasks]
tweak-configs = { depends-on = [
    "tweak-thaumicjei",
    "tweak-tinkersoredictcache",
    "tweak-relauncher",
] }
setup-gml = { cmd = "chmod +x ./gml/gml-linux", depends-on = [
    "prepare-gml",
    "download-gml",
    "unzip-gml",
] }
setup-forge = { cmd = 'java -cp "forge-install-bootstrapper.jar:forge-1.12.2-14.23.5.2860-installer.jar" com.bangbang93.ForgeInstaller ./.minecraft/', cwd = "gml", depends-on = [
    "download-forge-installer",
    "download-forge-bootstrapper",
] }
setup-jdk = { cmd = "chmod +x ./jdk-21.0.7+6/bin/java", depends-on = [
    "download-jdk",
    "unzip-jdk",
] }
build-ftbq-lang = { cmd = "python runners/build_ftbq_lang.py" }

[tasks.test-modpack]
cmd = "xvfb-run ./gml-linux -run 1.12.2-forge-14.23.5.2860 -username tester -ram 6144 -log -independent=f -javapath $JAVA_HOME_8_X64/bin/java"
cwd = "gml"
args = [
    { "arg" = "cf_token", "default" = "wtf" },
    { "arg" = "dir", "default" = "./mods" },
    { "arg" = "index", "default" = "./.minecraft/mods/.index" },
]
depends-on = [
    "setup-jdk",
    "setup-gml",
    "download-minecraft",
    "enable-hard-fail-script",
    "setup-modpack",
    "set-profile",
    "setup-forge",
    { "task" = "download-mods", "args" = [
        "{{ cf_token }}",
        "{{ dir }}",
        "{{ index }}",
    ] },
    "enable-hdsu",
    "enable-autostop",
    "tweak-configs",
]

[tasks.enable-hdsu]
cmd = "find ./hdsu_dev/hdsu -maxdepth 1 -type f -name '*.jar' ! -name '*-dev.jar' ! -name '*-sources.jar' -exec mv '{}' ./gml/.minecraft/mods ';'"

[tasks.enable-hard-fail-script]
cmd = [
    "mv",
    "./.minecraft/scripts/hardfail.zs.disabled",
    "./.minecraft/scripts/hardfail.zs",
]

[tasks.download-mods]
args = [
    { "arg" = "cf_token", "default" = "wtf" },
    { "arg" = "dir", "default" = "./mods" },
    { "arg" = "index", "default" = "./.minecraft/mods/.index" },
    { "arg" = "side", "default" = "both" },
    { "arg" = "black_list", "default" = "454215" },
]
cmd = "python runners/download_mods.py '{{ cf_token }}' {{ dir }} {{ index }} {{ side }} {{ black_list }}"

[tasks.enable-autostop]
cmd = ["mv", "./runners/autostop-1.0.jar", "./gml/.minecraft/mods"]

[tasks.tweak-thaumicjei]
cmd = [
    "mv",
    "./runners/thaumicjei.cfg",
    "./gml/.minecraft/config/thaumicjei.cfg",
]

[tasks.tweak-tinkersoredictcache]
cmd = [
    "mv",
    "./runners/tinkersoredictcache.cfg",
    "./gml/.minecraft/config/tinkersoredictcache.cfg",
]

[tasks.setup-modpack]
cmd = "mv ./.minecraft/* ./gml/.minecraft"

[tasks.prepare-gml]
cmd = "mkdir -p ./gml"

[tasks.download-gml]
cmd = "wget --no-verbose --timestamping https://github.com/xmdhs/gomclauncher/releases/download/v1.5.1/gml-linux.gz"
outputs = ["gml-linux.gz"]
cwd = "gml"

[tasks.unzip-gml]
cmd = "gzip -dk ./gml/gml-linux.gz"

[tasks.download-minecraft]
cmd = './gml-linux -downver 1.12.2 -type "vanilla" -independent=f'
cwd = "gml"

[tasks.download-forge-installer]
cmd = 'wget --no-verbose --timestamping https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-installer.jar'
cwd = "gml"

[tasks.download-forge-bootstrapper]
cmd = 'wget --no-verbose --timestamping https://github.com/bangbang93/forge-install-bootstrapper/releases/download/v0.3.0/forge-install-bootstrapper.jar'
cwd = "gml"

[tasks.download-jdk]
cmd = "wget --no-verbose --timestamping https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.7%2B6/OpenJDK21U-jdk_x64_linux_hotspot_21.0.7_6.tar.gz"
outputs = ["OpenJDK21U-jdk_x64_linux_hotspot_21.0.7_6.tar.gz"]

[tasks.unzip-jdk]
cmd = "tar -xzf OpenJDK21U-jdk_x64_linux_hotspot_21.0.7_6.tar.gz"

[tasks.set-profile]
cmd = 'echo "{\"selectedProfile\": \"(Default)\",\"profiles\": {\"(Default)\": {\"name\": \"(Default)\"}},\"clientToken\": \"88888888-8888-8888-8888-888888888888\"}" > ./gml/.minecraft/launcher_profiles.json'

[tasks.enable-relauncher]
cmd = ["mv", "./runners/++relauncher-0.3.11-beta.jar", "./gml/.minecraft/mods"]
depends-on = ["config-relauncher-dir"]

[tasks.config-relauncher-dir]
cmd = "mkdir -p relauncher"

[tasks.tweak-relauncher]
# cmd = 'echo "{\"selectedVersion\":\"0.3.4-alpha\",\"latestVersion\":\"0.3.4-alpha\",\"javaPath\":\"$(pwd)/jdk-21.0.7+6/bin/java\"}" > ./gml/.minecraft/config/relauncher.json'
cmd = "python runners/build_relauncher_cfg.py --java-path $(pwd)/jdk-21.0.7+6/bin/java --library-path $(pwd)/relauncher"
cwd = "."
depends-on = ["enable-relauncher"]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
tqdm = ">=4.67.1, <5"
loguru = ">=0.7.3, <0.8"
rtoml = ">=0.12.0, <0.13"
httpx = ">=0.28.1, <0.29"
minijinja = ">=2.10.2, <3"
