name: TestRunner
on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  TestRunner:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: ${{ github.event_name == 'push' }}
        uses: styfle/cancel-workflow-action@0.12.1

      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2
          cache: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'zulu'

      - name: Restore assets
        id: runner-download-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ./relauncher
          key: ${{ runner.os }}-runner-download-cache

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: develop_build.yml
          workflow_search: false
          workflow_conclusion: success
          ref: trunk
          name: hdsu
          name_is_regexp: true
          path: hdsu_dev
          repo: ProjectHDS/HerodotusUtils
          check_artifacts: false
          skip_unpack: false
          if_no_artifact_found: fail
          allow_forks: false
          use_unzip: false

      - name: Run game test
        run: pixi run test-modpack '${{ secrets.CF_TOKEN }}' ./gml/.minecraft/mods ./gml/.minecraft/mods/.index 

      - name: Save assets
        id: runner-download-cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ./relauncher
          key: ${{ steps.runner-download-cache-restore.outputs.cache-primary-key }}